[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["src/files/brand_data.json"]
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"